In [1]:
import numpy as np
import pandas as pd

In [2]:
thing = pd.DataFrame(np.arange(9).reshape(3, 3), columns=['a', 'b', 'c'])

In [3]:
thing

   a  b  c
0  0  1  2
1  3  4  5
2  6  7  8

In [4]:
thing1 = thing.astype({'a': np.float}); thing1

     a  b  c
0  0.0  1  2
1  3.0  4  5
2  6.0  7  8

In [5]:
thing2 = thing1.astype({'b': 'category'})

In [6]:
thing2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 3 columns):
a    3 non-null float64
b    3 non-null category
c    3 non-null int32
dtypes: category(1), float64(1), int32(1)
memory usage: 223.0 bytes